### ISSUE TITLE
Failure when parsing secondary EXE for diff

### ISSUE THREAD

**Issue by fenderluvr** [telerik/JustAssembly#57]
Files comparing are 4mb in size.  Below is the error:

Object reference not set to an instance of an object.
   at JustAssembly.Nodes.TypeNode.CleanExceptionSource(IDecompilationResults decompilationResult, String sourceCode) in C:\Jenkins\ReleaseFullWithUploadBuild\workspace\UI\JustAssembly\Nodes\TypeNode.cs:line 99
   at JustAssembly.Nodes.TypeNode.GetDifferenceDecoration() in C:\Jenkins\ReleaseFullWithUploadBuild\workspace\UI\JustAssembly\Nodes\TypeNode.cs:line 166
   at JustAssembly.Nodes.TypeNode..ctor(IOldToNewTupleMap`1 typesMap, ItemNodeBase parent, APIDiffInfo apiDiffInfo, FilterSettings filterSettings) in C:\Jenkins\ReleaseFullWithUploadBuild\workspace\UI\JustAssembly\Nodes\TypeNode.cs:line 39
   at JustAssembly.Nodes.NamespaceNode.GenerateTypeNode(IOldToNewTupleMap`1 metadataTuple, LoadAPIItemsContext context) in C:\Jenkins\ReleaseFullWithUploadBuild\workspace\UI\JustAssembly\Nodes\NamespaceNode.cs:line 65
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
   at JustAssembly.Nodes.NamespaceNode.LoadChildren() in C:\Jenkins\ReleaseFullWithUploadBuild\workspace\UI\JustAssembly\Nodes\NamespaceNode.cs:line 47
   at ICSharpCode.TreeView.SharpTreeNode.EnsureLazyChildren()
   at ICSharpCode.TreeView.SharpTreeNode.set_IsExpanded(Boolean value)
   at JustAssembly.Nodes.ModuleNode.<>c__DisplayClass8_0.<LoadChildren>b__1(IGrouping`2 g) in C:\Jenkins\ReleaseFullWithUploadBuild\workspace\UI\JustAssembly\Nodes\ModuleNode.cs:line 53
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
   at JustAssembly.Nodes.ModuleNode.LoadChildren() in C:\Jenkins\ReleaseFullWithUploadBuild\workspace\UI\JustAssembly\Nodes\ModuleNode.cs:line 50
   at ICSharpCode.TreeView.SharpTreeNode.EnsureLazyChildren()
   at ICSharpCode.TreeView.SharpTreeNode.set_IsExpanded(Boolean value)
   at JustAssembly.Nodes.AssemblyNode.GenerateModuleNode(IOldToNewTupleMap`1 metadataTuple, LoadAPIItemsContext context, Boolean shouldBeExpanded) in C:\Jenkins\ReleaseFullWithUploadBuild\workspace\UI\JustAssembly\Nodes\AssemblyNode.cs:line 315
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at JustAssembly.Nodes.AssemblyNode.GetMergedModules(Boolean shouldBeExpanded) in C:\Jenkins\ReleaseFullWithUploadBuild\workspace\UI\JustAssembly\Nodes\AssemblyNode.cs:line 303
   at JustAssembly.Nodes.AssemblyNode.<>c__DisplayClass29_0.<LoadItemsAsync>b__1() in C:\Jenkins\ReleaseFullWithUploadBuild\workspace\UI\JustAssembly\Nodes\AssemblyNode.cs:line 194

**Comment by atdimitrov** [comment]
Would it be possible to attach the assemblies needed for reproduction?

**Comment by bsivanov** [comment]
Probably duplicate of #23.
